import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
export default function Home({filteredCoins, broadInfo}) {
  return (
    <div>
      <Head>
        <title>Shayp Coins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar broadInfo={broadInfo}/>
      <h1>Welcome to Shayp!</h1>
    </div>
  )
}

export async function getServerSideProps() {
  const [filteredCoinsRes, broadInfoRes, converterRes] = await Promise.all([
    fetch('https://api.coinpaprika.com/v1/coins'),
    fetch('https://api.coinpaprika.com/v1/global'),
    fetch('https://api.coinpaprika.com/v1/price-converter')
  ]);
  const [filteredCoins, broadInfo, converter] = await Promise.all([
    filteredCoinsRes.json(),
    broadInfoRes.json(),
    converterRes.json()
  ]);
  return { props: { filteredCoins, broadInfo, converter } };
}
