import Head from 'next/head'
import Navbar from '../components/Navbar'
import Table from '../components/Table'
import styles from '../styles/Home.module.css'
export default function Home({filteredCoins, broadInfo}) {
  console.log({filteredCoins});
  return (
    <div className={styles.main_container}>
      <Head>
        <title>Shayp Coins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar broadInfo={broadInfo}/>
      <h1>Welcome to Shayp!</h1>
      <Table filteredCoins={filteredCoins} />
    </div>
  )
}

export async function getServerSideProps() {
  const [broadInfoRes, converterRes, filteredCoinsRes] = await Promise.all([
    fetch('https://api.coinpaprika.com/v1/global'),
    fetch('https://api.coinpaprika.com/v1/price-converter'),
    require( 'coinpaprika-js' )
  ]);
  const [broadInfo, converter, filteredCoins] = await Promise.all([
    broadInfoRes.json(),
    converterRes.json(),
    filteredCoinsRes.tickers()
  ]);
  return { props: {broadInfo, converter, filteredCoins} };
}
